// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VillaCenter_Api.Data;

#nullable disable

namespace VillaCenter_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230502211129_AlimientarTablaVilla")]
    partial class AlimientarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VillaCenter_Api.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            CreatedAt = new DateTime(2023, 5, 2, 15, 11, 29, 510, DateTimeKind.Local).AddTicks(1597),
                            Detalle = "Detalle de la Villa",
                            ImagenUrl = "",
                            MetrosCuadrados = 10,
                            Nombre = "Villa Real inicial",
                            Ocupantes = 5,
                            Tarifa = 100.0,
                            UpdatedAt = new DateTime(2023, 5, 2, 15, 11, 29, 510, DateTimeKind.Local).AddTicks(1614)
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            CreatedAt = new DateTime(2023, 5, 2, 15, 11, 29, 510, DateTimeKind.Local).AddTicks(1617),
                            Detalle = "Detalle de la Villa",
                            ImagenUrl = "",
                            MetrosCuadrados = 150,
                            Nombre = "Premium Villa",
                            Ocupantes = 12,
                            Tarifa = 200.0,
                            UpdatedAt = new DateTime(2023, 5, 2, 15, 11, 29, 510, DateTimeKind.Local).AddTicks(1618)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
